const colors = {
  light: {
    text: "#0D0B14",
    tint: "#6C47FF",
    background: "#F7F5FF",
    foreground: "#0D0B14",
    card: "#FFFFFF",
    cardForeground: "#0D0B14",
    primary: "#6C47FF",
    primaryForeground: "#FFFFFF",
    secondary: "#EEE9FF",
    secondaryForeground: "#4B2FD4",
    muted: "#F0EDF8",
    mutedForeground: "#9B9BA4",
    accent: "#FF6B9D",
    accentForeground: "#FFFFFF",
    success: "#00C896",
    successForeground: "#FFFFFF",
    warning: "#FFB800",
    warningForeground: "#FFFFFF",
    destructive: "#FF4757",
    destructiveForeground: "#FFFFFF",
    border: "#E8E4F4",
    input: "#E8E4F4",
    income: "#00C896",
    expense: "#FF4757",
  },

  dark: {
    text: "#F7F5FF",
    tint: "#8B6FFF",
    background: "#0D0B14",
    foreground: "#F7F5FF",
    card: "#1A1626",
    cardForeground: "#F7F5FF",
    primary: "#8B6FFF",
    primaryForeground: "#FFFFFF",
    secondary: "#211A32",
    secondaryForeground: "#C4ADFF",
    muted: "#1A1626",
    mutedForeground: "#6B6B7B",
    accent: "#FF6B9D",
    accentForeground: "#FFFFFF",
    success: "#00C896",
    successForeground: "#FFFFFF",
    warning: "#FFB800",
    warningForeground: "#FFFFFF",
    destructive: "#FF4757",
    destructiveForeground: "#FFFFFF",
    border: "#2A2340",
    input: "#2A2340",
    income: "#00C896",
    expense: "#FF6B9D",
  },

  radius: 16,
};

export default colors;
